name: greenpark's CI
run-name: ${{ github.actor }} is CI work

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
