name: greenpark's CI
run-name: ${{ github.actor }} is CI work

on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Start CI work"
